services:
  open-webui:
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    depends_on: {}

  api:
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    depends_on: {}
